name: FreeBSD 14

on: [push, pull_request]

jobs:
  freebsd-14:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
      matrix:
        shells:
          - {shell: sh}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: SH="${{ matrix.shells.shell }}" contrib/various_test.sh

