name: NetBSD 9

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  netbsd-9:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        shells:
          - {shell: sh}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        release: "9.3"
        run: SH="${{ matrix.shells.shell }}" contrib/various_test.sh
